dist: bionic
group: edge
language: python
services:
  - docker

# Travis use depth=50 by default. Use 1 for faster cloning.
git:
  depth: 1

jobs:
  include:
    - env: DIST=centos-8  TARGETS="storage tests"
    - env: DIST=centos-8  TARGETS="lint"

before_install:
  - docker --version
  - docker pull vjuranek/vdsm-test-$DIST

before_script:
  # autogen.sh needs a tag, but the last tag may be 100 commits in the past,
  # and we don't want to get the entire history for testing the tip.
  - git tag v999 -a -m "tesing"

# Notes:
# - network tests on centos fail on low coverage, so we use lower value.
# - mount /run/udev to enable tests receiving udev events.
script:
  - |
    docker run \
    --env TRAVIS_CI=1 \
    --env PYLINT_JOBS=1 \
    --env NETWORK_COVERAGE=38 \
    --privileged \
    --rm \
    -it \
    --volume `pwd`:/vdsm:Z \
    --volume /run/udev:/run/udev:Z \
    --volume /dev/log:/dev/log:Z \
    quay.io/ovirt/vdsm-test-$DIST \
    bash -c "cd /vdsm && travis/test.sh $TARGETS"
