sudo: required
dist: xenial
group: edge
language: python
services:
  - docker

# Travis use depth=50 by default. Use 1 for faster cloning.
git:
  depth: 1

# Notes: we run the linters only on Fedora 29 to save time. This may miss some
# issues on CentOS but the chance is very low.
env:
  matrix:
    - DIST=centos-7   PY=2.7  TARGETS="storage tests"
    - DIST=fedora-29  PY=3.7  TARGETS="lint"
    - DIST=fedora-29  PY=2.7  TARGETS="storage tests"
    - DIST=fedora-29  PY=3.7  TARGETS="storage tests"
    - DIST=fedora-30  PY=3.7  TARGETS="storage tests"

matrix:
  allow_failures:
    - env: DIST=fedora-30  PY=3.7  TARGETS="storage tests"

before_install:
  - docker --version
  - docker pull vjuranek/vdsm-test-$DIST

before_script:
  # autogen.sh needs a tag, but the last tag may be 100 commits in the past,
  # and we don't want to get the entire history for testing the tip.
  - git tag v999 -a -m "tesing"

# Notes:
# - network tests on centos fail on low coverage, so we use lower value.
# - mount /run/udev to enable tests receiving udev events.
script:
  - |
    docker run \
    --env TRAVIS_CI=1 \
    --env PYLINT_JOBS=1 \
    --env NETWORK_PY27_COVERAGE=38 \
    --env NETWORK_PY36_COVERAGE=38 \
    --privileged \
    --rm \
    -it \
    --volume `pwd`:/vdsm:Z \
    --volume /run/udev:/run/udev:Z \
    vjuranek/vdsm-test-$DIST \
    bash -c "cd /vdsm && ./autogen.sh --system --with-only-python=python$PY && make all $TARGETS"
